var $patches_opt = {
    "build.source":"light",
    "build.registry.software":"merge",
    "build.catalog":"auto",
    "build.wow64support":true,
    "account.admin_enabled":false,
    "account.autologon_countdown":5,
    "account.admin_screen":"wallpaper",
    "system.darktheme":false,
    "theme.title_color":"8",
    "config.fbwf.cache":"128GB",
    "config.computername":"Edgeless",
    "system.workgroup":"WORKGROUP",
    "system.high_compatibility":true,
    "shell.app":"explorer",
    "tweak.shortcut.noarrow":true,
    "tweak.shortcut.nosuffix":true,
    "component.MMC":true,
    "component.DWM":true,
    "component.vcruntime":true,
    "component.mspaint":true,
    "component.winphotoviewer":true,
    "IE.x64_component":"x64+x86",
    "IE.custom_settings":true,
    "IE.home_page":"about:blank",
    "network.function_discovery":true,
    "network.builtin_drivers":true,
    "slim.winboot":true,
    "build.cmd_mode":false,
    "build.cmd_mode_code":"MODE 150,9999",
    "build.registry.system_driverdatabase":"merge",
    "build.registry.drivers":"merge",
    "account.localized_admin_name":"Administrator",
    "account.custom_admin_name":"Administrator",
    "adk.wpe_path":"C:\\Program Files (x86)\\Windows Kits\\10\\Assessment and Deployment Kit\\Windows Preinstallation Environment",
    "adk.lang":"zh-CN",
    "desktop.iconsize":"48",
    "shell.use_theme_color":false,
    "shell.startmenu":"StartAllBack",
    "SIB.version":"*",
    "SIB.programs.flyout":false,
    "policy.lmcompatlevel":"2",
    "network.trayicon":false,
    "network.full_functional":true,
    "network.type_builtin_drivers":"default",
    "component.dsmsvc":true,
    "MTP.mtphelper":"mtpHelper.sys",
    "IME.indicator":true,
    "IME.system_ime":false,
    "IME.ms_pinyin":true,
    "IME.ms_Phonetic":false,
    "component.notepad":true,
    "7-zip.selected_assoc_exts":"7z,zip,rar,cab,iso,xz,tar,bzip2,gz,gzip,wim",
    "material.location":"X:",
    "material.load_mode":"auto",
    "PEMApp.chrome":false,
    "PEMApp.chrome.type":"INST",
    "PEMApp.chrome.dl_url":"https://dl.google.com/release2/chrome/AMQFLHv8Muh_ExYptfSwv2g_81.0.4044.113/81.0.4044.113_chrome_installer.exe",
    "mycustom.theme_id":"1",
    "slim.mui":true,
    "slim.winre_sources":true,
    "slim.font.mingliu":true,
    "slim.wbem_repository":true,
    "slim.speech":true,
    "slim.hive_drivers":true,
    "slim.hive_software":true,
    "slim.hive_system":true,
    "slim.hive_components":true,
    "vbox.version":"auto",
    "shell.wallpaper":"%APP_ROOT%\\%APPDATA_DIR%\\_CustomFiles_\\wallpaper.jpg",
    "build.preprocess_wim":false,
    "build.mount_wim_action":"built_in",
    "build.load_hive":true,
    "build.precommit_wim":true,
    "build.commit_wim_action":"built_in",
    "build.custom_iso":true,
    "build.preprocess_wim_script":"_00-Ô¤´¦ÀíWIMÓ³Ïñ.bat",
    "build.mount_wim_script":"_10-¹ÒÔØWIMÓ³Ïñ.bat",
    "build.precommit_wim_script":"_80-Ô¤Ìá½»WIMÓ³Ïñ.bat",
    "build.commit_wim_script":"_90-±£´æWIMÓ³Ïñ.bat",
    "component.taskmgr":true,
    "component.bitlocker":true,
    "component.search":true,
    "patch.drvinst":true,
    "build.registry.system":false,
    "build.full_catalog":false,
    "loader.name":"pecmd",
    "loader.PEMaterial":"PEMaterial",
    "system.power.off_disp_bat":0,
    "system.power.off_disp_plug":0,
    "system.power.off_disk_bat":20,
    "system.power.off_disk_plug":0,
    "system.power.dis_usb_suspend_bat":true,
    "system.power.dis_usb_suspend_plug":true,
    "system.volume_level":50,
    "system.volume_mute":false,
    "system.numlock":true,
    "account.SYSTEM_logon_pass":"",
    "account.admin_logon_pass":"",
    "account.admin_password":"",
    "account.admin_autologon":true,
    "account.precreate_admin_profile":false,
    "shell.light_theme":true,
    "shell.show_thisPC":true,
    "shell.show_recyclebin":true,
    "shell.taskbar.combine":"always",
    "shell.fix.showDesktop":true,
    "shell.ui.resolution":true,
    "shell.clockarea.event":true,
    "shell.system.property":true,
    "shell.shortcut.ocf":true,
    "shell.fix.fullscreen":true,
    "component.PPPoE":false,
    "network.hide_system_tray_icon":true,
    "network.networklist_and_sharecenter":true,
    "audio.win_events":"base",
    "audio.hide_system_tray_icon":true,
    "component.MTP":true,
    "component.RNDIS":true,
    "component.printer":true,
    "component.bluetooth":true,
    "component.camera":true,
    "IME.ms_wubi":false,
    "IME.ms_Quick":false,
    "IME.ms_Cangjie":false,
    "IME.cht_DaYi":false,
    "IME.cht_Array":false,
    "mstsc.enable_credssp_support":false,
    "component.termservice":true,
    "component.wordpad":false,
    "component.snippingtool":true,
    "component.accessibility":false,
    "component.MSI":true,
    "component.netfx":true,
    "component.opengl":true,
    "component.directx":true,
    "appcompat.property_page":true,
    "appcompat.assistant":false,
    "slim.ieframedll":false,
    "slim.jscript":true,
    "slim.hta":true,
    "slim.wmi":false,
    "slim.small_fonts":true,
    "slim.small_imageresdll":true,
    "slim.safe":true,
    "slim.extra":false,
    "slim.hive":true,
    "iso.attended_boot":false,
    "iso.edit_bcd":true,
    "iso.loading_progress":true,
    "iso.x_exFAT":false,
    "custom.restart_explorer_menu":true,
    "custom.restart_explorer_item":"ÖØÆô×ÀÃæ½ø³Ì",
    "custom.show_cmd_menu":true,
    "winxshell.ui_volume.startup":true,
    "winxshell.ui_volume.no_beep":false,
    "winxshell.ui_wifi.startup":false,
    "SIB.skin":"Plain10",
    "SIB.style.opaque":true,
    "driver.load_basic_display_demand":false,
    "imdisk.ramdisk":false,
    "imdisk.drive_letter":"B:",
    "imdisk.disk_size":"2048",
    "adk.oc_setup.LegacySetup":false,
    "adk.oc_setuo.Setup":false,
    "adk.oc_setup.Setup-Client":false,
    "adk.oc_setup.Setup-Server":false,
    "adk.oc_setup.SecureStartup":false,
    "adk.oc_net.Dot3Svc":false,
    "adk.oc_net.PPPoE":false,
    "adk.oc_net.RNDIS":false,
    "adk.oc_net.WDS-Tools":false,
    "adk.oc.PlatformId":true,
    "adk.oc.PowerShell":true,
    "adk.oc.SecureBootCmdlets":true,
    "adk.oc.StorageWMI":true,
    "adk.oc.MDAC":true,
    "adk.oc.FMAPI":true,
    "adk.oc.HTA":false,
    "adk.oc.NetFx":true,
    "adk.oc.GamingPeripherals":true,
    "adk.oc.WinReCfg":true,
    "adk.oc.Scripting":true,
    "adk.oc.WMI":true,
    "adk.oc.EnhancedStorage":true,
    "adk.oc.PmemCmdlets":true,
    "adk.fonts.legacy":false,
    "adk.font.WinRE":false,
    "adk.font.ja-JP":false,
    "adk.font.ko-KR":false,
    "adk.font.zh-CN":true,
    "adk.font.zh-HK":false,
    "adk.font.zh-TW":false,
    "_._._":""
}

function patches_state_init() {
    uncheck_tree_node("_CustomFiles_");
    open_tree_node("_CustomFiles_");
    check_tree_node("00-Configures");
    open_tree_node("00-Configures");
    uncheck_tree_node("01-Components/00-Boot2WinRE");
    check_tree_node("01-Components/00-Shell/Explorer");
    check_tree_node("01-Components/00-Shell/WinXShell");
    select_tree_node("01-Components/00-Shell/WinXShell");
    uncheck_tree_node("01-Components/00-Shell/za-StartMenu/Classic Shell");
    check_tree_node("01-Components/00-Shell/za-StartMenu/StartIsBack");
    open_tree_node("01-Components/00-Shell/za-StartMenu");
    open_tree_node("01-Components/00-Shell");
    check_tree_node("01-Components/02-Network");
    check_tree_node("01-Components/03-Audio");
    check_tree_node("01-Components/CredDialog");
    check_tree_node("01-Components/Devices and Printers");
    check_tree_node("01-Components/IME");
    uncheck_tree_node("01-Components/Internet Explorer");
    check_tree_node("01-Components/Remote Desktop");
    uncheck_tree_node("01-Components/Windows Media Player");
    check_tree_node("01-Components/za-Accessories");
    check_tree_node("01-Components/zh-RuntimeKits");
    open_tree_node("01-Components");
    check_tree_node("01-Drivers/00-SystemDrivers");
    uncheck_tree_node("01-Drivers/10-CustomDrivers");
    open_tree_node("01-Drivers");
    check_tree_node("02-Apps/7-Zip");
    uncheck_tree_node("02-Apps/Defraggler");
    uncheck_tree_node("02-Apps/Explorer++");
    uncheck_tree_node("02-Apps/HotSwap");
    uncheck_tree_node("02-Apps/ImDisk");
    check_tree_node("02-Apps/Notepad3");
    check_tree_node("02-Apps/PENetwork");
    uncheck_tree_node("02-Apps/yong_IME");
    open_tree_node("02-Apps");
    uncheck_tree_node("02-PEMaterial");
    open_tree_node("02-PEMaterial");
    check_tree_node("10-MyCustom/00-MyLoader.LINK");
    check_tree_node("10-MyCustom/00-MySystem.LINK");
    uncheck_tree_node("10-MyCustom/01-MyDrivers.LINK");
    uncheck_tree_node("10-MyCustom/10-MyApps.LINK");
    uncheck_tree_node("10-MyCustom/11-MyMaterial.LINK");
    open_tree_node("10-MyCustom/11-MyMaterial.LINK");
    check_tree_node("10-MyCustom/MyContextMenu.LINK");
    uncheck_tree_node("10-MyCustom/MyStartMenu.LINK");
    uncheck_tree_node("10-MyCustom/MyTheme.LINK");
    open_tree_node("10-MyCustom.LINK");
    check_tree_node("za-Slim");
    uncheck_tree_node("za-SlimUltra");
    uncheck_tree_node("zy-Test");
    open_tree_node("zy-Test");
    check_tree_node("zz-ISO");
    check_tree_node("zz-Utils");
    open_tree_node("zz-Utils");
}
