name: Build Release
on:
    push:
      branches: [master]
      tags:
        - "release-*"
        - "beta-*"
        - "alpha-*"

jobs:
  task:
    runs-on: windows-latest
    steps:
      - name: wimbuilder2
        run: |
          aria2c "https://onemanager-one-virid.vercel.app/main/wimbuilder2.zip"
          7z x wimbuilder2.zip -owimbuilder2
          del wimbuilder2.zip
      - uses: actions/checkout@v3
        with:
          path: ./Wimbuilder2/AppData/Projects
      - name: windows 11 22000.739
        run: |
          aria2c "https://onemanager-one-virid.vercel.app/main/os/zh-cn_windows_11_business_editions_updated_june_2022_x64_dvd_0b165f6d.iso"
      - name: MountWindowsImageAndBuild
        shell: pwsh
        run: |
          $mountResult = Mount-DiskImage ${{ github.workspace }}\zh-cn_windows_11_business_editions_updated_june_2022_x64_dvd_0b165f6d.iso -PassThru
          $driveLetter = ($mountResult | Get-Volume).DriveLetter
          ${{ github.workspace }}\wimbuilder2\WimBuilder.cmd --build-with-log --source-folder ${driveLetter}: --source-index 2 --make-iso --close-ui
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}\wimbuilder2\_Factory_\BOOTPE.iso